### ISSUE TITLE
problem with new prompt option

### ISSUE THREAD

**Issue by BillH99999** [tekezo/disable_dnd_tb#4]
First of all I love your plugin.  This really should be built into Thunderbird.  I also really like the new option to prompt if you want to allow the move.  This is how the old extension I used to use worked.  It saves having to enable and disable the plugin anytime I really want to move a folder.

I did run into a problem with this new option however.  It works great when dragging a folder to a new location.   However, when I tried to drag a message from one folder to another I got this pop-up window.

![image1](https://user-images.githubusercontent.com/26846819/116278876-c2521380-a73b-11eb-8fc9-4a7a833233bd.jpg)

I shouldn't get this as I'm dragging a message in the message pane to a folder in the folder pane, I'm not trying to drag a folder in the folder pane to another location in the folder pane. 
 
Thanks,
Bill

**Comment by tekezo** [comment]
Thank you for feedback!
I confirmed this issue. Please wait a moment while I fix it.

**Comment by tekezo** [comment]
I fixed this issue at v4.10.0. Please confirm it.

**Comment by BillH99999** [comment]
The problem worked after I first installed 4.10.0.  Then later I did a reboot and it stopped working.  I disabled the extension and re-enabled it and then it started working again.  Seems like something isn't quite right yet.

Thanks,
Bill

**Comment by tekezo** [comment]
The add-on works well even after restarted on my machine.

What exactly do you mean by not working?

- Example 1: The folder is moved without prompt.
- Example 2: The folder is not moved, but the prompt is not shown.

**Comment by BillH99999** [comment]
Sorry, I should have been more clear.

I am not trying to move a folder... I am trying to move a message from one folder to another.  I get the prompt asking if I really want to move the folder even though I am trying to move a message.  If I click on OK, the message is still not moved.  I shouldn't get the prompt at all when moving messages, they should just move.

As I said in my other messages, it sometimes works and sometimes doesn't.  This doesn't appear to be related to whether or not I do a reboot.  It seems that when it isn't working if I disable the extension and then re-enable it, it works fine for awhile and then stops working.

Thanks,
Bill

**Comment by tekezo** [comment]
As for the messages, the prompts have been removed in v4.10.0, but does that mean they still show up occasionally?

**Comment by BillH99999** [comment]
Yes, this is happening in 4.10.0.

Bill

**Comment by tekezo** [comment]
Hmm, I can't reproduce it here.
Do you use any other add-ons together?

**Comment by BillH99999** [comment]
Hi,

Sorry for the delay in responding, I just woke up.  Last night when I went to bed I was getting the prompt when trying to move a message from one folder to another.  I woke up this morning and now it I am not getting the prompt.

I use the following extensions:

CardBook    58.6.2
changeQuote    1.5.1
ColumnsWizard    8.0.0-b6
Disable DragAndDrop (Thunderbird)
EditEmailSubject MX    4.3
Folder Account    10.0
Manually sort folders   2.0.6 
Message Header Toolbar Customize    2.1.0
No Message Pane Sort    2.0
Preferences Button    1.1
Quote Colors    2.0.7 
Remove Duplicate Messages    0.5.1b2
tbkeys-lite    2.1.1
Toggle Headers    3.0

**Comment by BillH99999** [comment]
I was gone all morning and when I came back just now I am again getting the prompt when trying to move messages.  So I tried disabling all add-ons except for Disable DragAndDrop (Thunderbird).  This didn't help as I am still getting the prompt.

**Comment by tekezo** [comment]
Thank you for extensions information!

Due to the limitation of Thunderbird add-on API, the prompt uses very tricky way, so it may have been affected by other add-ons.
I've tried to fix it, so could you confirm v4.10.1? (You can download v4.10.1 from Download button in the following page.)

https://github.com/pqrs-org/disable-draganddrop-tb/blob/master/xpi/disable_dnd_tb-4.10.1.xpi

**Comment by BillH99999** [comment]
I installed 4.10.1 and at the moment it is working fine.  I'll keep an eye on it for awhile and see if it stops working.

Thanks for the quick turnaround on a new version.

Bill

**Comment by BillH99999** [comment]
I have been moving messages at intervals during the day and have not had the prompt window appear.  Everything has worked as expected.  I'm about ready to go to bed, so I'll check in the morning and it is still working without the prompt window then it looks like you got it fixed in 4.10.1.

Bill

**Comment by BillH99999** [comment]
I checked again this morning and it is still working.... no prompt when moving messages.

Thanks!
Bill

**Comment by tekezo** [comment]
Thanks!
I'll release v4.10.1 as v4.11.0.

**Comment by tekezo** [comment]
I've released v4.11.0.
https://addons.thunderbird.net/en-US/thunderbird/addon/disable-draganddrop-tb-v2/

**Comment by BillH99999** [comment]
Thanks again!

Bill
